[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright"]
indent = { tab-width = 4, unit = "    " }
auto-format = false

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode="off"
autoImportCompletions = true

[[language]]
name = "typescript"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server" ]

[[language]]
name = "zig"
file-types = ["zig", "zon"]
language-servers = [ "zls" ]

[[language]]
name = "c"
file-types = ["c", "h", "cpp", "cc", "hpp", "hh"]
language-servers = [ "clangd" ]

[language-server.clangd.config]
fallbackFlags = ["-std=c++20"]
