[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright"]
indent = { tab-width = 4, unit = "    " }
auto-format = false

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode="off"
autoImportCompletions = true

[[language]]
name = "typescript"
file-types = ["ts"]
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server" ]

[language-server.typescript-language-server.config.typescript]
# Ensure this setting is present or add it
# This enables the "Add all missing imports" source action
code_action_context = { only = ["source.addMissingImports.ts"] }

[[language]]
name = "zig"
file-types = ["zig", "zon"]
language-servers = [ "zls" ]

[[language]]
name = "haskell"
file-types = ["hs"]
language-servers = [ "haskell-language-server-wrapper" ]

[[language]]
name = "c"
file-types = ["c", "h"]
language-servers = [ "clangd" ]

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "hpp", "hh"]
language-servers = [ "clangd" ]

[[language]]
name = "clojure"
file-types = ["clj", "edn"]
language-servers = [ "clojure-lsp" ]

[[language]]
name = "go"
file-types = ["go"]
language-servers = [ "gopls" ]
